# Generated by Django 4.2.10 on 2024-05-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_cart',
        ),
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
